global java.util.ArrayList ruleNames;

import com.example.drools.model.RiskRequest;
import com.example.drools.rules.Rule
import com.example.drools.rules.CountryCodeRule
import com.example.drools.rules.EmailRule
import com.example.drools.rules.CustomerNumberRule


dialect "mvel"

rule "Germany Rules"
    when
        RiskRequest(countryCode == "DE")
    then
        ruleNames.add("CountryCodeRule");
        ruleNames.add("EmailRule");
        insert(ruleNames)
    end

rule "Israel Rules"
    when
        RiskRequest(countryCode == "IL")
    then
        ruleNames.add("CountryCodeRule");
        ruleNames.add("CustomerNumberRule");
        insert(ruleNames)
    end